package cn.ac.iie.docker.wrapper.conf;

/**
 * @author Fighter Created on 2018/9/29.
 */
public interface Constants {
    String DOCKER_HOST = "DOCKER_HOST";
    String DOCKER_TLS_VERIFY = "DOCKER_TLS_VERIFY";
    String REGISTRY_URL = "REGISTRY_URL";
    String REGISTRY_USERNAME = "REGISTRY_USERNAME";
    String REGISTRY_PASSWORD = "REGISTRY_PASSWORD";
    String DOCKER_READ_TIMEOUT = "DOCKER_READ_TIMEOUT";
    String DOCKER_CONNECT_TIMEOUT = "DOCKER_CONNECT_TIMEOUT";
    String DOCKER_MAX_TOTAL_CONNECTIONS = "DOCKER_MAX_TOTAL_CONNECTIONS";
    String DOCKER_MAX_PER_ROUTE_CONNNECTIONS = "DOCKER_MAX_PER_ROUTE_CONNNECTIONS";
}
